[[constraint]]
  name = "github.com/caarlos0/env"
  version = "3.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  name = "github.com/pressly/goose"
  version = "2.3.0"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.3.0"

[prune]
  go-tests = true
  unused-packages = true
